################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
adc \
aodv \
aomdv \
apps \
asim \
baytcp \
chargingsys/app \
chargingsys \
chargingsys/mac \
chargingsys/phy \
chargingsys/routing \
classifier \
common \
delaybox \
diffserv \
diffusion \
diffusion3/apps/gear_examples \
diffusion3/apps/ping \
diffusion3/apps/rmst_examples \
diffusion3/filter_core \
diffusion3/filters/diffusion \
diffusion3/filters/gear \
diffusion3/filters/misc \
diffusion3/filters/rmst \
diffusion3/lib \
diffusion3/lib/main \
diffusion3/lib/nr \
diffusion3/ns \
doc/figures \
dsdv \
dsr \
empweb \
emulate \
gaf \
gen \
imep \
indep-utils/cmu-scen-gen/setdest \
indep-utils/dosdbell \
indep-utils/dosreduce \
indep-utils/model-gen \
indep-utils/propagation \
indep-utils/webtrace-conv/dec \
indep-utils/webtrace-conv/epa \
indep-utils/webtrace-conv/nlanr \
indep-utils/webtrace-conv/ucb \
lib \
link \
linkstate \
mac \
mcast \
mobile \
mpls \
nix \
. \
packmime \
pgm \
plm \
pushback \
qs \
queue \
rap \
realaudio \
routealgo \
routing \
satellite \
sctp \
sensor-nets \
src_rtg \
tcl/test \
tcp \
tcp/linux \
tcp/linux/src \
tmix \
tools \
tora \
trace \
webcache \
wpan \
xcp \

