#!/usr/bin/env perl

set term png
set title 'Data generated by All Nodes - Latency'
set output "AllNode_latency.png"
set xlabel "data generation interval in sec" font "Helvetica,16"
set ylabel "latency in ms" font "Helvetica,16"
plot [] [:50000] 'data/3_AllNode_Latency.txt' title 'Node 3' with lines, 'data/7_AllNode_Latency.txt' title 'Node 7' with lines, 'data/15_AllNode_Latency.txt' title 'Node 15' with lines

set term png
set title 'Data generated by Edge Nodes - Latency'
set output "EdgeNode_latency.png"
set xlabel "data generation interval in sec" font "Helvetica,16"
set ylabel "latency in ms" font "Helvetica,16"
plot [] [:5000] 'data/3_EdgeNode_Latency.txt' title 'Node 3' with lines, 'data/7_EdgeNode_Latency.txt' title 'Node 7' with lines, 'data/15_EdgeNode_Latency.txt' title 'Node 15' with lines

set term png
set title 'Data generated by All Nodes - Drop Ratio'
set output "AllNode_drop.png"
set xlabel "data generation interval in sec" font "Helvetica,16"
set ylabel "drop ratio" font "Helvetica,16"
plot [] [:10] 'data/3_AllNode_drop.txt' title 'Node 3' with lines, 'data/7_AllNode_drop.txt' title 'Node 7' with lines, 'data/15_AllNode_drop.txt' title 'Node 15' with lines

set term png
set title 'Data generated by Edge Nodes - Drop Ratio'
set output "EdgeNode_drop.png"
set xlabel "data generation interval in sec" font "Helvetica,16"
set ylabel "drop ratio" font "Helvetica,16"
plot [] [:10] 'data/3_EdgeNode_drop.txt' title 'Node 3' with lines, 'data/7_EdgeNode_drop.txt' title 'Node 7' with lines, 'data/15_EdgeNode_drop.txt' title 'Node 15' with lines

set term png
set title 'All Node vs Edge Node - Latency, N=15'
set output "edge_all_node15_latency.png"
set xlabel "data generation interval in sec" font "Helvetica,16"
set ylabel "latency in ms" font "Helvetica,16"
plot [] [:50000] 'data/15_EdgeNode_Latency.txt' title 'Edge Node' with lines, 'data/15_AllNode_Latency.txt' title 'All Node' with lines

set term png
set title 'All Node vs Edge Node - Drop Ratio, N=15'
set output "edge_all_node15_drop.png"
set xlabel "data generation interval in sec" font "Helvetica,16"
set ylabel "drop ratio" font "Helvetica,16"
plot [] [] 'data/15_EdgeNode_drop.txt' title 'Edge Node' with lines, 'data/15_AllNode_drop.txt' title 'All Node' with lines



